import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  guideSidebar: [
    'welcome',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/installation',
        'getting-started/setup',
      ],
    },
    {
      type: 'category',
      label: 'Create Maps',
      items: [
        'map/map-interface',
        'map/editing-notes',
        'map/arc',
        'map/bubble',
        'map/moving-bubble',
      ],
    },
    {
      type: 'category',
      label: 'Create Visuals',
      items: [
        {
          type: 'autogenerated',
          dirName: 'visual',
        },
      ]
    },
    'saving',
    'testing',
    'publishing',
    'controls',
    'faq',
  ],
};

export default sidebars;